# Written by wing. It records which template generated this project and what each
# file looked like at the time, so `wing template update` can tell a file you edited
# from one the template changed. Commit it.

template = "rust"
name = "atom"
generated_at = "2026-09-02T07:46:16Z"

[[files]]
path = ".env.lua"
hash = "f92c9d1444b37be0b1858eedea22f250"

[[files]]
path = ".github/workflows/release.yml"
hash = "783dd4b7c59ee8fac764960ca820373d"

[[files]]
path = ".github/workflows/tests.yml"
hash = "927278f544005e809480b4ef63410301"

[[files]]
path = ".gitignore"
hash = "8f180a52eb62a15f7271c52ef628f01f"

[[files]]
path = ".make.lua"
hash = "10922afacce5794f6bea98ca3a1a574c"

[[files]]
path = "Cargo.toml"
hash = "3ad486f44642369887f58e38e828d199"

[[files]]
path = "PROJECT"
hash = "6d22ac56fcdd0236640324a3fd5e303a"

[[files]]
path = "README.md"
hash = "1684e116423932ae686723b3432ef286"

[[files]]
path = "examples/main.rs"
hash = "bc28c844cbace70f12b39b776079a8b0"

[[files]]
path = "flake.nix"
hash = "0077d9c1efa0dcc143ae83e9a7efa8d0"

[[files]]
path = "src/lib.rs"
hash = "f7c7b5edafbcb782bdd85ebcc754be3f"

